baseURL = "/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Doug"
    author = "Douglas Vinícius"
    description = "Estatística & Concurso."
    copyright = "doug"
    useDarkTheme = true

   [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="sigma.png">
        <link rel="icon" type="image/png" sizes="16x16" href="sigma.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="sigma.png">
        '''

    # Profile section
    [params.profile]
        name = "Douglas Vinícius"
        tagline = "Estatística & Concurso."
        location = "Rondônia, BR"
        photo = "754349main_butterfly_nebula_full_full.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/public-profile/settings?trk=d_flagship3_profile_self_view_public_profile"
            title = "LinkedIn"		
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/Doug7Vinicius"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-stack-overflow"
            url = "https://stackoverflow.com/users/11490202/douglas-vin%C3%ADcius?tab=profile"
            title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/Douglas69572577"
            title = "Twitter"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "posts"    
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "Sobre Mim"
        icon = "fas fa-user"
        description = "Sou apenas um rapaz..."

    # Experience section
    [params.experience]
        title = "Experiência"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Job Title"
            dates = "2019 - *Present*"
            company = "Company Name"
            details = "Printed from desktop. Sent [emails](#). Called people using telephone. Drank water from office cooler. Ate donuts on people's birthdays."
        [[params.experience.list]]
            position = "Auxiliar Administrativo Nível I"
            dates = "2016 - 2018"
            link = ""
            company = "CentralCredisis"

    # Education section
    [params.education]
        title = "Educação"
        icon = "fas fa-graduation-cap"

#        [[params.education.list]]
#            degree = "Ph.D. in Subject"
#            college = "University of State-City"
#            dates = "2013 - 2018"
#            thesis_title = "Effect of humans on other humans: a study of human behavior."
#            thesis_link = "#"
#        [[params.education.list]]
#            degree = "M.S. in Subject"
#            college = "University of State-City"
#            dates = "2013 - 2018"
#            thesis_title = "Effect of humans on other humans: a study of human behavior."
#            thesis_link = "#"
        [[params.education.list]]
            degree = "Bacharel em Estatística"
            college = "Universidade Federal de Rondônia"
            dates = "2015 - 2020"

    # Publication section
    [params.publication]
        title = "Publicações"
        icon = "fas fa-book"

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
    
    # Project Posts
    [params.posts]
        title = "Posts"
        icon = "fas fa-chart-line"
        
        [[params.posts.list]]
            title = "Introdução a MySQL com R"
            date = ""
            link = "#"
        
    # Project section
    [params.project]
        title = "Projetos"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Português"
            url = "#"
            description = "Língua Portuguesa."
        [[params.project.list]]
            title = "Estatística Descritiva"
            url = "#"
            description = "Estatística descritiva e análise exploratória de dados."
        [[params.project.list]]
            title = "Probabilidade"
            url = "#"
            description = "Teoria da Probabilidade."
        [[params.project.list]]
            title = "Inferência"
            url = "#"
            description = "Inferência Estatística."
        [[params.project.list]]
            title = "Análise de Regressão Linear"
            url = "#"
            description = "Análise de Regressão Linear."
        [[params.project.list]]
            title = "Amostragem"
            url = "#"
            description = "Técnias de Amostragem."

    # Skill section
    [params.skill]
        title = "Habilidades"
        icon = "fas fa-cogs"


        [[params.skill.list]]
            skill = "Português"
            skillrating = 90
        [[params.skill.list]]
            skill = "Estatística Descritiva"
            skillrating = 80
        [[params.skill.list]]
            skill = "Probabilidade"
            skillrating = 50
        [[params.skill.list]]
            skill = "Inferência"
            skillrating = 70
        [[params.skill.list]]
            skill = "Análise de Regressão Linear"
            skillrating = 70
        [[params.skill.list]]
            skill = "Técnicas de Amostragem"
            skillrating = 70    
    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]		
            hobby = "Violoncelo"
        [[params.hobby.list]]		
            hobby = "Astronomia"
        [[params.hobby.list]]		
            hobby = "Xadrez"
